export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#003798",
        secondary: "#5f5f62",
        "on-tertiary-container": "#4f4964",
        "inverse-primary": "#618bff",
        "on-error-container": "#752121",
        "surface-tint": "#0053db",
        "on-tertiary-fixed": "#3c3650",
        "secondary-fixed-dim": "#d5d3d8",
        "on-tertiary-fixed-variant": "#59526e",
        "primary-container": "#dbe1ff",
        error: "#9f403d",
        "on-secondary": "#faf8fc",
        outline: "#477dbb",
        "on-secondary-fixed-variant": "#5b5b5f",
        "primary-dim": "#0048c1",
        tertiary: "#625b77",
        "surface-container-high": "#dce9ff",
        primary: "#0053db",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#e5eeff",
        surface: "#f8f9ff",
        background: "#f8f9ff",
        "on-secondary-container": "#515155",
        "surface-dim": "#c4dcff",
        "tertiary-container": "#dfd5f7",
        "error-dim": "#4e0309",
        "surface-variant": "#d2e4ff",
        "inverse-surface": "#000f21",
        "tertiary-fixed-dim": "#d0c7e8",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#dfd5f7",
        "secondary-fixed": "#e4e2e6",
        "secondary-dim": "#535356",
        "surface-container-highest": "#d2e4ff",
        "surface-bright": "#f8f9ff",
        "on-error": "#fff7f6",
        "error-container": "#fe8983",
        "inverse-on-surface": "#8e9eb7",
        "on-primary-fixed-variant": "#0050d4",
        "on-secondary-fixed": "#3f3f43",
        "surface-container-low": "#eff4ff",
        "on-background": "#00345e",
        "on-primary-container": "#0048bf",
        "on-surface-variant": "#26619d",
        "outline-variant": "#81b5f6",
        "tertiary-dim": "#564f6b",
        "on-surface": "#00345e",
        "secondary-container": "#e4e2e6",
        "primary-fixed-dim": "#c7d3ff",
        "on-primary": "#f8f7ff",
        "on-tertiary": "#fdf7ff",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  // eslint-disable-next-line no-undef
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
